### ISSUE TITLE
nsss is not mentioned as an optional dependency

### ISSUE THREAD

**Issue by firasuke** [skarnet/utmps#2]
Hey there,

The `configure` script clearly states that `nsss` could be used with `utmps`, but I didn't find `nsss` listed as an optional dependency on the [website](https://skarnet.org/software/utmps/) (unlike `execline`, `s6`, `s6-linux-init` and `mdevd` where it's clearly mentioned as an optional dependency there both in the `configure` script and on the website)..

Is this intended?

Thanks in advance

**Comment by skarnet** [comment]
It's kinda intentional, because I wanted to keep the documentation as simple as possible - this is a simple and very low-level piece of software, but susceptible to be used by any person running musl - no need to confuse them with an option that would only ever be used by a distribution switching entirely to nsss.

People who build a distribution with nsss would know to enable the option on utmps.

It's not very important, but until nsss gets more widespread, I think the statu quo is better.

**Comment by firasuke** [comment]
I see, thanks for elaborating on that.

Closing...
